set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/.vim/bundle')
"
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Colorscheme
syntax enable

" enable mouse
set mouse=a

" show whitespace
set list
set listchars=trail:.

"autoremove whitespace EOL
autocmd BufWritePre * :%s/\s\+$//e

" Spaces & tabs
set encoding=utf-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set expandtab
vnoremap < <gv
vnoremap > >gv

" Display Interface
set number 			" show line number
set showcmd 			" show command bar in the bottom


" Catching filetype
filetype indent on		" each filetype uses the filetype.vim in the indent folder

" Wildmenu
set wildmenu

" Lazy redraw to gain perf
set lazyredraw

" highlighting
set showmatch
set incsearch
set hlsearch
set ignorecase

" removing swap file
set noswapfile

" folding
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent

" moving
nnoremap j gj
nnoremap k gk

" leader
let mapleader=","

" fugitive
Plugin 'tpope/vim-fugitive'

" Syntastic
Plugin 'scrooloose/syntastic'

" open Nerdtree
Plugin 'scrooloose/nerdtree'
map <tab> :NERDTreeToggle<CR>

" open CTRLP
Plugin 'kien/ctrlp.vim'

" Vim Airline
Plugin 'bling/vim-airline'

" Colorscheme
Plugin 'tomasr/molokai'

" Php indenting
Plugin '2072/PHP-Indenting-for-VIm'
set autoindent

" debugger
Bundle 'joonty/vdebug.git'

" Note
Plugin 'xolox/vim-notes'

" configuration for airline
set laststatus=2

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
